language: node_js
dist: trusty
node_js: '6'
before_script: npm install
script:
- npm run test
- npm run build
after_success: npm run coverage
deploy:
  provider: npm
  email: sebastian.lzy@gmail.com
  api_key:
    secure: eWmOufTZjszudhn7zmiDUjq3X2f3GhcWa0inrxXb7SIgZauJT5FAjJsQAKNd8JtypGLgR9YHcKaUkhWEnvgQ1WPdkPK4xFpo71uJ6d/T7N2D0gZ0DKTtkY8GQOySNRI35/ime1pUeAsIePi8MWHy5C3Q+Po+xIbpG5mMxAwtU5rGr+oMKllsay6NwfPcze145mWUkPN3N2ZiqiKeMuc0Kc7p2a29bx/JGkEPpxG+833QjpoaaUqkPnZVgJLZDewDavCQX745/xn3C5YWthyb6Z3skfjGrCB5UiBRybnT10xqXbIabbe6LiJouLVdDyiRI6Ylu9fk4wtjEQ451CGc+270IROVzgnOf3Izwo2lf2NtPyePYkhmsKJPtnDoy0xB2hfXRxnDnKw2u+FsTuTdonTI0f24NMAwU+jCXAULt6nta640IZUGrWMIhJVnaa7MoYpe1VDK9OCcYBIYjA8WYtjRWycHa/A3nqwl+5D1DvIa//haAhV+pW/+ZCTfQ8qTIUprRlUcpYZfpLQ3gOwJcLQIWP77Lcpry7mjHy59LWNIP4WC8eFY0HDjlRmmxV+uuicjeM/BSBQ0L50uR79SXFa2jk56kjhsUGPbTR91HK5zolj3o7OK0hAncVvUOk0pPvta+la1Wf2LPBdO7c/PG1b/McvserZyyijXY92y2to=
  on:
    tags: true
    repo: sebastianlzy/json-hashable
